# Generated by Django 5.0.4 on 2025-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='incorporation_date',
            field=models.DateField(blank=True, help_text='Date of incorporation of the organization', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Permanent Account Number (PAN) of the organization', max_length=20, null=True),
        ),
    ]
